// Code generated by hertz generator.

package main

import (
	demo "project2/biz/handler/hertz/demo"

	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	h := server.Default()

	register(h)
	demo.InitGenericClient("studentservice")
	h.Spin()
}
