// Code generated by hertz generator.

package main

import (
	demo "hertz-project/biz/handler/hertz/demo"
	"github.com/cloudwego/hertz/pkg/app/server"

	"net/http"
	_ "net/http/pprof"
)

func main() {

	// push test by Leo


	//to test through pprof
	go http.ListenAndServe("localhost:8080",nil)
	h := server.Default()

	demo.InitGenericClient("studentservice")
	register(h)

	h.Spin()
}
